name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        run: actions/setup-node@v2.5.1

      - name: Build
        run: |
          npm install
          npm run build
      
      - name: GH Pages deploy
        uses: Cecilapp/GitHub-Pages-deploy@3.2.1
        with:
          build_dir: dist
          branch: gh-pages
          
